listener 8883 0.0.0.0
protocol mqtt
cafile /path/to/pico-pqc-sigbench/certlab/mldsa44/ca.cert.pem
certfile /path/to/pico-pqc-sigbench/certlab/mldsa44/server.cert.pem
keyfile /path/to/pico-pqc-sigbench/certlab/mldsa44/server.key.pem
require_certificate true
use_identity_as_username false
tls_version tlsv1.3
