#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
main="$root/mqtt_client/main.c"
tls="$root/mqtt_client/tls_transport.c"
cmake="$root/mqtt_client/CMakeLists.txt"
lwipopts="$root/mqtt_client/lwipopts.h"
settings="$root/config/wolfssl/tls/user_settings.h"
config="$root/mqtt_client/config.h"
mqtt="$root/mqtt_client/mqtt.c"
memory="$root/mqtt_client/runtime_memory.c"

grep -q 'cyw43_tcpip_link_status(&cyw43_state, CYW43_ITF_STA)' "$main"
! grep -q 'cyw43_wifi_link_status(&cyw43_state, CYW43_ITF_STA)' "$main"
grep -q 'cyw43_arch_wifi_connect_async' "$main"
grep -q 'cyw43_arch_init_with_country(CYW43_COUNTRY_SINGAPORE)' "$main"
grep -q 'sync_time_with_sntp' "$main"
grep -q 'sntp_setservername' "$main"
grep -q 'SNTP_SET_SYSTEM_TIME' "$lwipopts"
grep -q 'SNTP_SERVER_DNS' "$lwipopts"
grep -q 'wolfTLSv1_3_client_method' "$tls"
grep -q 'SSL_VERIFY_PEER' "$tls"
grep -q 'wolfSSL_UseSupportedCurve(c->ssl, WOLFSSL_X25519MLKEM768)' "$tls"
grep -q 'wolfSSL_UseKeyShare(c->ssl, WOLFSSL_X25519MLKEM768)' "$tls"
grep -q 'wolfSSL_CTX_use_certificate_buffer' "$tls"
grep -q 'wolfSSL_CTX_use_PrivateKey_buffer' "$tls"
grep -q 'tls_handshake_rx_bytes' "$tls"
grep -q 'tls_handshake_tx_bytes' "$tls"
grep -q 'tls_get_bandwidth' "$tls"
grep -q 'tls_connect_attempt' "$tls"
grep -q 'TLS_FAILURE_TLS_HANDSHAKE' "$tls"
grep -q 'runtime_memory_wolfssl_malloc' "$tls"
grep -q 'stack_high_water_bytes' "$memory"
grep -q 'mallinfo().uordblks' "$memory"
grep -q 'DISCOVERY_TOPIC "homeassistant/device/picow_pq/config"' "$config"
grep -q 'STATE_TOPIC     "picow_pq/state"' "$config"
grep -q 'STATUS_TOPIC    "picow_pq/status"' "$config"
grep -q 'DISCOVERY_TOPIC "homeassistant/device/pico2w_pq/config"' "$config"
grep -q 'STATE_TOPIC     "pico2w_pq/state"' "$config"
grep -q 'STATUS_TOPIC    "pico2w_pq/status"' "$config"
grep -q 'mqtt_publish_retained' "$main"
grep -q 'mqtt_connect_with_will' "$main"
grep -q 'Handshake traffic: rx=' "$main"
grep -q 'TLS record bytes only' "$main"
grep -q 'Plain-MQTT' "$main"
grep -q 'csv_hs_header,scheme,board,campaign,run' "$main"
grep -q 'success,failure_stage,error_code,timeout' "$main"
grep -q 'RSA-2048' "$main"
grep -q 'tls_connect_plain' "$main"
grep -q 'mqtt_publish_qos0' "$mqtt"
grep -q 'PKT_PUBLISH | (retain ? 0x01 : 0x00)' "$mqtt"
grep -q 'will_retain' "$mqtt"
grep -q 'value_json.temperature_c' "$main"
grep -q 'value_json.humidity_percent' "$main"
! grep -q 'cyw43_arch_poll' "$main"
! grep -q 'cyw43_arch_poll' "$tls"

grep -q 'pico_cyw43_arch_lwip_threadsafe_background' "$cmake"
grep -q 'pico_lwip_sntp' "$cmake"
! grep -q 'pico_cyw43_arch_lwip_poll' "$cmake"
! grep -q '^#define NO_ASN_TIME' "$settings"
grep -q '^#define WOLFSSL_HAVE_MLKEM' "$settings"
grep -q '^#define WOLFSSL_WC_MLKEM' "$settings"
grep -q '^#define WOLFSSL_PQC_HYBRIDS' "$settings"
grep -q '^#define WOLFSSL_NO_ML_KEM_512' "$settings"
grep -q '^#define WOLFSSL_NO_ML_KEM_1024' "$settings"

grep -q 'SIGBENCH_BOARD_NAME' "$cmake"
grep -q 'MQTT_BOARD_PICOW' "$cmake"
grep -q 'MQTT_BOARD_PICO2W' "$cmake"
grep -q 'mqtt_client_hawk512' "$cmake"
grep -q 'MQTT_SCHEME_HAWK512' "$cmake"
grep -q 'certs/certs_hawk512.h' "$main"
grep -q 'certs/certs_ecdsa_p256.h' "$main"
grep -q 'certs/certs_rsa2048.h' "$main"
grep -q '#define BROKER_PORT_HAWK512     8885' "$config"
grep -q '#define BROKER_PORT_MAYO1       8884' "$config"
grep -q '#define BROKER_PORT_MLDSA44     8883' "$config"
grep -q '#define BROKER_PORT_ECDSA_P256  8880' "$config"
grep -q '#define BROKER_PORT_RSA2048     8881' "$config"
grep -q '#define BROKER_PORT_PLAIN       1883' "$config"
grep -q 'defined(MQTT_TRANSPORT_PLAIN)' "$config"
grep -q 'defined(MQTT_SCHEME_HAWK512)' "$config"
grep -q 'defined(MQTT_SCHEME_MAYO1)' "$config"
grep -q 'defined(MQTT_SCHEME_ECDSA_P256)' "$config"
grep -q 'defined(MQTT_SCHEME_RSA2048)' "$config"
grep -q 'mqtt_client_ecdsa_p256' "$cmake"
grep -q 'mqtt_client_rsa2048' "$cmake"
grep -q 'plain_transport.c' "$cmake"
grep -q 'mqtt_client_plain' "$cmake"

echo "PASS: MQTT client uses background WiFi/IP processing, TLS 1.3 mTLS, and plain MQTT"
