#!/usr/bin/env bash
#
# gen_client_cert.sh - generate a PQ client certificate signed by the
# Mosquitto broker's CA, then emit C arrays ready to paste into the
# matching mqtt_client/certs/certs_<scheme>.h file.
#
# Prerequisites:
#   openssl with oqs-provider installed, e.g.:
#     https://github.com/open-quantum-safe/oqs-provider
#   Tested with oqs-provider 0.7.x + OpenSSL 3.3+
#
# Usage:
#   ./tools/gen_client_cert.sh [--scheme mldsa44|falcon512|mayo1] <ca_cert> <ca_key> [outdir]
#
# The CA cert/key are the same files your Mosquitto uses.
# Default output directory: mqtt_client/certs/
# Default scheme: mldsa44
#
set -euo pipefail

SCHEME="mldsa44"

# Parse --scheme before positional args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --scheme)
            SCHEME="${2:?--scheme requires an argument (mldsa44|falcon512|mayo1)}"
            shift 2
            ;;
        --scheme=*)
            SCHEME="${1#--scheme=}"
            shift
            ;;
        *)
            break
            ;;
    esac
done

CA_CERT="${1:?Usage: $0 [--scheme mldsa44|falcon512|mayo1] <ca_cert> <ca_key> [outdir]}"
CA_KEY="${2:?Usage: $0 [--scheme mldsa44|falcon512|mayo1] <ca_cert> <ca_key> [outdir]}"
OUTDIR="${3:-$(dirname "$0")/../mqtt_client/certs}"

case "$SCHEME" in
    mldsa44|falcon512|mayo1) ;;
    *) echo "ERROR: unknown scheme '$SCHEME' (expected mldsa44, falcon512, or mayo1)"; exit 1 ;;
esac

mkdir -p "$OUTDIR"

OPENSSL="${OPENSSL:-openssl}"
OQS_MODULE="${OQS_MODULE:-/usr/lib/x86_64-linux-gnu/ossl-modules/oqsprovider.so}"

echo "[+] Checking oqs-provider..."
"$OPENSSL" list -providers -provider-path "$(dirname "$OQS_MODULE")" \
    -provider oqsprovider -provider default | grep -q oqsprovider \
    || { echo "ERROR: oqs-provider not found at $OQS_MODULE"; exit 1; }

PROV_ARGS="-provider-path $(dirname "$OQS_MODULE") -provider oqsprovider -provider default"

echo "[+] Generating ${SCHEME} client key..."
# shellcheck disable=SC2086
"$OPENSSL" genpkey $PROV_ARGS \
    -algorithm "$SCHEME" \
    -out "$OUTDIR/client_${SCHEME}.key.pem"

echo "[+] Creating CSR..."
# shellcheck disable=SC2086
"$OPENSSL" req $PROV_ARGS \
    -new \
    -key "$OUTDIR/client_${SCHEME}.key.pem" \
    -subj "/CN=pico2w-pq/O=PicoMQTT" \
    -out "$OUTDIR/client_${SCHEME}.csr"

echo "[+] Signing CSR with broker CA..."
# shellcheck disable=SC2086
"$OPENSSL" x509 $PROV_ARGS \
    -req \
    -days 3650 \
    -in  "$OUTDIR/client_${SCHEME}.csr" \
    -CA  "$CA_CERT" \
    -CAkey "$CA_KEY" \
    -CAcreateserial \
    -out "$OUTDIR/client_${SCHEME}.cert.pem"

echo "[+] Converting to DER..."
"$OPENSSL" x509 -in "$OUTDIR/client_${SCHEME}.cert.pem" \
    -outform DER -out "$OUTDIR/client_${SCHEME}.cert.der"
# shellcheck disable=SC2086
"$OPENSSL" pkey $PROV_ARGS -in "$OUTDIR/client_${SCHEME}.key.pem" \
    -outform DER -out "$OUTDIR/client_${SCHEME}.key.der"
CA_DER="$OUTDIR/ca_${SCHEME}.cert.der"
"$OPENSSL" x509 -in "$CA_CERT" -outform DER -out "$CA_DER"

echo "[+] Generating C arrays..."
emit_array() {
    local label="$1" file="$2"
    printf "static const uint8_t %s[] = {\n" "$label"
    xxd -i < "$file" | sed '/^unsigned int .*_len = /d'
    printf "};\nstatic const size_t %s_LEN = sizeof(%s);\n\n" "$label" "$label"
}

# Determine output header filename
if [ "$SCHEME" = "mldsa44" ]; then
    OUT_HEADER="$OUTDIR/certs.h"
else
    OUT_HEADER="$OUTDIR/certs_${SCHEME}.h"
fi

{
    printf "/* AUTO-GENERATED by tools/gen_client_cert.sh --scheme %s - do not edit manually */\n" "$SCHEME"
    printf "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n"
    emit_array "MQTT_CA_CERT_DER"      "$CA_DER"
    emit_array "MQTT_CLIENT_CERT_DER"  "$OUTDIR/client_${SCHEME}.cert.der"
    emit_array "MQTT_CLIENT_KEY_DER"   "$OUTDIR/client_${SCHEME}.key.der"
} > "$OUT_HEADER"

echo "[+] Written: $OUT_HEADER"
echo ""

case "$SCHEME" in
    mldsa44) TARGET="mqtt_client_mldsa44" ;;
    falcon512) TARGET="mqtt_client_falcon512" ;;
    mayo1) TARGET="mqtt_client_mayo1" ;;
esac

echo "    Rebuild the firmware with: cmake --build build-pico2w --target ${TARGET}"
echo ""
echo "    Also configure Mosquitto to require client certs signed by:"
echo "      $CA_CERT"
