#!/usr/bin/env bash
#
# import_client_cert.sh - import existing MQTT mTLS material into the
# scheme-specific C header compiled into the Pico W / Pico 2 W UF2.
#
# Usage:
#   ./tools/import_client_cert.sh --scheme mldsa44 <ca_cert> <client_cert> <client_key> [outdir]
#
# Supported schemes:
#   mldsa44, falcon512, mayo1, snova_24_5_16_4, ecdsa_p256, rsa2048
#
# Inputs may be PEM or DER. For post-quantum private keys, set OQS_MODULE so
# OpenSSL can load oqsprovider before converting the key to DER.
set -euo pipefail

SCHEME="mldsa44"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --scheme)
            SCHEME="${2:?--scheme requires an argument}"
            shift 2
            ;;
        --scheme=*)
            SCHEME="${1#--scheme=}"
            shift
            ;;
        *)
            break
            ;;
    esac
done

CA_CERT="${1:?Usage: $0 [--scheme mldsa44|falcon512|mayo1|snova_24_5_16_4|ecdsa_p256|rsa2048] <ca_cert> <client_cert> <client_key> [outdir]}"
CLIENT_CERT="${2:?Usage: $0 [--scheme mldsa44|falcon512|mayo1|snova_24_5_16_4|ecdsa_p256|rsa2048] <ca_cert> <client_cert> <client_key> [outdir]}"
CLIENT_KEY="${3:?Usage: $0 [--scheme mldsa44|falcon512|mayo1|snova_24_5_16_4|ecdsa_p256|rsa2048] <ca_cert> <client_cert> <client_key> [outdir]}"
OUTDIR="${4:-$(dirname "$0")/../mqtt_client/certs}"

case "$SCHEME" in
    mldsa44|falcon512|mayo1|snova_24_5_16_4|ecdsa_p256|rsa2048) ;;
    *) echo "ERROR: unknown scheme '$SCHEME' (expected mldsa44, falcon512, mayo1, snova_24_5_16_4, ecdsa_p256, or rsa2048)" >&2; exit 1 ;;
esac

OPENSSL="${OPENSSL:-openssl}"
PROV_ARGS=()

if [[ -n "${OQS_MODULE:-}" ]]; then
    OQS_PROVIDER_DIR="${OQS_PROVIDER_DIR:-$(dirname "$OQS_MODULE")}"
    PROV_ARGS=(-provider-path "$OQS_PROVIDER_DIR" -provider oqsprovider -provider default)
    echo "[+] Checking oqs-provider..."
    "$OPENSSL" list -providers "${PROV_ARGS[@]}" | grep -q oqsprovider \
        || { echo "ERROR: oqs-provider not found via OQS_MODULE=$OQS_MODULE" >&2; exit 1; }
fi

mkdir -p "$OUTDIR"

CA_DER="$OUTDIR/ca_${SCHEME}.cert.der"
CLIENT_CERT_DER="$OUTDIR/client_${SCHEME}.cert.der"
CLIENT_KEY_DER="$OUTDIR/client_${SCHEME}.key.der"

convert_cert_to_der() {
    local input="$1"
    local output="$2"

    if "$OPENSSL" x509 -in "$input" -outform DER -out "$output" 2>/dev/null; then
        return
    fi
    "$OPENSSL" x509 -inform DER -in "$input" -outform DER -out "$output"
}

convert_key_to_der() {
    local input="$1"
    local output="$2"

    if [[ ${#PROV_ARGS[@]} -gt 0 ]]; then
        if "$OPENSSL" pkey "${PROV_ARGS[@]}" -in "$input" -outform DER -out "$output" 2>/dev/null; then
            return
        fi
        "$OPENSSL" pkey "${PROV_ARGS[@]}" -inform DER -in "$input" -outform DER -out "$output"
    else
        if "$OPENSSL" pkey -in "$input" -outform DER -out "$output" 2>/dev/null; then
            return
        fi
        "$OPENSSL" pkey -inform DER -in "$input" -outform DER -out "$output"
    fi
}

echo "[+] Importing CA certificate..."
convert_cert_to_der "$CA_CERT" "$CA_DER"

echo "[+] Importing client certificate..."
convert_cert_to_der "$CLIENT_CERT" "$CLIENT_CERT_DER"

echo "[+] Importing client private key..."
convert_key_to_der "$CLIENT_KEY" "$CLIENT_KEY_DER"

emit_array() {
    local label="$1" file="$2"
    printf "static const uint8_t %s[] = {\n" "$label"
    xxd -i < "$file" | sed '/^unsigned int .*_len = /d'
    printf "};\nstatic const size_t %s_LEN = sizeof(%s);\n\n" "$label" "$label"
}

if [[ "$SCHEME" = "mldsa44" ]]; then
    OUT_HEADER="$OUTDIR/certs.h"
else
    OUT_HEADER="$OUTDIR/certs_${SCHEME}.h"
fi

{
    printf "/* AUTO-GENERATED by tools/import_client_cert.sh --scheme %s - do not edit manually */\n" "$SCHEME"
    printf "#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n"
    emit_array "MQTT_CA_CERT_DER" "$CA_DER"
    emit_array "MQTT_CLIENT_CERT_DER" "$CLIENT_CERT_DER"
    emit_array "MQTT_CLIENT_KEY_DER" "$CLIENT_KEY_DER"
} > "$OUT_HEADER"

echo "[+] Written: $OUT_HEADER"
echo "[+] Rebuild the matching target before flashing."
